// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "about-rubikpi", // 文档 ID
      label: "关于魔方派", // 侧边栏标签
    },
    {
      type: "doc",
      id: "notice", // 文档 ID
      label: "魔方派使用须知", // 侧边栏标签
    },
    {
      type: "category",
      label: "RUBIK Pi 3 用户手册",
      collapsed: false,
      // link: {type: 'doc', id: 'rubik-pi-3-user-manual/1.0.0-a/get-started'},
      items: [
         {
          type: "category",
          label: "Ubuntu System",
          collapsed: false,
          // 默认展开

          // link: {type: 'doc', id: 'rubik-pi-3-user-manual/1.0.0-a/get-started'},
            link: {
            type: "generated-index",
            title: "Ubuntu System",
            description:
              "更新日期：2025年08月12日，版本：1.0.0",
            slug: "/rubik-pi-3/cn/docs/1.0.0-u",
            
            // keywords: ["guides"],
            // image: "/img/docusaurus.png",
            },
            
            items: [
            {
              type: 'autogenerated',
              dirName: 'rubik-pi-3-user-manual/1.0.0-u', // 指定要自动生成的目录路径
            },
            ],
          // items: [
          //   "rubik-pi-3-user-manual/1.1.2/get-started",
          //   "rubik-pi-3-user-manual/1.1.2/peripherals-and-interfaces",
          //   "rubik-pi-3-user-manual/1.1.2/qualcomm-ai-hub",
          //   "rubik-pi-3-user-manual/1.1.2/ai-developer-workflow",
          //   "rubik-pi-3-user-manual/1.1.2/qualcomm-im-sdk",
          //   "rubik-pi-3-user-manual/1.1.2/lvgl-user-guide",
          //   "rubik-pi-3-user-manual/1.1.2/qt5-user-guide",
          //   "rubik-pi-3-user-manual/1.1.2/tools-and-libraries-porting-guide",
          //   "rubik-pi-3-user-manual/1.1.2/ros-user-guide",
          //   "rubik-pi-3-user-manual/1.1.2/yocto-project-user-guide",
          //   "rubik-pi-3-user-manual/1.1.2/user-guide-to-rubikpi-config",
          //   "rubik-pi-3-user-manual/1.1.2/gitHub-operation-guide",
          //   "rubik-pi-3-user-manual/1.1.2/revision-history",
          // ],
        },
        {
          type: "category",
          label: "Linux System",
          // 默认展开
          
          // link: {type: 'doc', id: 'rubik-pi-3-user-manual/1.0.0-a/get-started'},
          link: {
            type: "generated-index",
            title: "Linux System",
            description:
              "更新日期：2025年06月06日，版本：1.1.2 | 基于 Qualcomm Linux 1.3",
            slug: "1.1.2",
            keywords: ["guides"],
            image: "/img/docusaurus.png",
          },
          items: [
            "rubik-pi-3-user-manual/1.1.2/get-started",
            "rubik-pi-3-user-manual/1.1.2/peripherals-and-interfaces",
            "rubik-pi-3-user-manual/1.1.2/qualcomm-ai-hub",
            "rubik-pi-3-user-manual/1.1.2/ai-developer-workflow",
            "rubik-pi-3-user-manual/1.1.2/qualcomm-im-sdk",
            "rubik-pi-3-user-manual/1.1.2/lvgl-user-guide",
            "rubik-pi-3-user-manual/1.1.2/qt5-user-guide",
            "rubik-pi-3-user-manual/1.1.2/tools-and-libraries-porting-guide",
            "rubik-pi-3-user-manual/1.1.2/ros-user-guide",
            "rubik-pi-3-user-manual/1.1.2/yocto-project-user-guide",
            "rubik-pi-3-user-manual/1.1.2/user-guide-to-rubikpi-config",
            "rubik-pi-3-user-manual/1.1.2/gitHub-operation-guide",
            // "rubik-pi-3-user-manual/1.1.2/revision-history",
          ],
        },
         {
          type: "category",
          label: "Android System",
          // 默认展开
          
          // link: {type: 'doc', id: 'rubik-pi-3-user-manual/1.0.0-a/get-started'},
          link: {
            type: "generated-index",
            title: "Android System",
            description:
              "更新日期：2025年06月06日，版本：1.0.1 | 基于 Android 13",
            slug: "1.0.1-a",
            keywords: ["guides"],
            image: "/img/docusaurus.png",
          },
          items: [
            "rubik-pi-3-user-manual/1.0.1-a/get-started",
            "rubik-pi-3-user-manual/1.0.1-a/peripherals-and-interfaces",
            "rubik-pi-3-user-manual/1.0.1-a/qualcomm-ai-hub",
            // "rubik-pi-3-user-manual/1.0.1-a/revision-history",
            
          ],
        },
        {
          type: "category",
          label: "Debian System",
          // 默认展开
          
          // link: {type: 'doc', id: 'rubik-pi-3-user-manual/1.0.0-a/get-started'},
          link: {
            type: "generated-index",
            title: "Debian System",
            description:
              "更新日期：2025年06月06日，版本：1.0.1 | 基于 Debian 13",
            slug: "1.0.1-d",
            keywords: ["guides"],
            image: "/img/docusaurus.png",
          },
          items: [
            "rubik-pi-3-user-manual/1.0.1-d/get-started",
            "rubik-pi-3-user-manual/1.0.1-d/peripherals-and-interfaces",
            "rubik-pi-3-user-manual/1.0.1-d/ai-processor-and-sdk-testing-methods",
            "rubik-pi-3-user-manual/1.0.1-d/user-guide-to-rubikpi-config",
            "rubik-pi-3-user-manual/1.0.1-d/github-operation-guide",
            // "rubik-pi-3-user-manual/1.0.1-d/revision-history",
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "peripheral-compatibility-list", // 文档 ID
      label: "外设兼容列表", // 侧边栏标签
    },
    {
      type: "doc",
      id: "hardware-resources", // 文档 ID
      label: "硬件资料", // 侧边栏标签
    },
    {
      type: "doc",
      id: "image", // 文档 ID
      label: "系统镜像", // 侧边栏标签
    },
    {
      type: "doc",
      id: "cybersecurity-certification", // 文档 ID
      label: "开放网络端口", // 侧边栏标签
    },
    {
      type: "doc",
      id: "development-regulatory-notice", // 文档 ID
      label: "开发监管公告", // 侧边栏标签
    },
    
    {
      type: "doc",
      id: "revision-center", // 文档 ID
      label: "版本中心", // 侧边栏标签
    },
  ],
  /**
   * Independent sidebars for specific historical versions of RUBIK Pi 3 user manual.
   * Docs inside these directories can opt-in by adding `sidebar: manual100Sidebar` (etc.)
   * in their front matter if you want to render them isolated from the main tutorialSidebar.
   */
  manual100Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'rubik-pi-3-user-manual/1.0.0',
    },
  ],
  manual110Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'rubik-pi-3-user-manual/1.1.0',
    },
  ],
  manual111Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'rubik-pi-3-user-manual/1.1.1',
    },
  ],

  manual100aSidebar: [
    {
      type: 'autogenerated',
      dirName: 'rubik-pi-3-user-manual/1.0.0-a',
    },
  ],
  manual100dSidebar: [
    {
      type: 'autogenerated',
      dirName: 'rubik-pi-3-user-manual/1.0.0-d',
    },
  ],
};

export default sidebars;
